package com.example.clas.db;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

import com.example.clas.bean.SearchBean;

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchBeanDaoConfig;

    private final SearchBeanDao searchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);

        registerDao(SearchBean.class, searchBeanDao);
    }
    
    public void clear() {
        searchBeanDaoConfig.clearIdentityScope();
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

}
